# Generated by Django 2.0.2 on 2018-04-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='billpay',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paytype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roomratings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'managed': True},
        ),
    ]
